import React from "react"

export const metadata = {
  title: "Nownownow | Mochammad Alif Pratama",
  description: "Generated by create next app",
}


const NowPage = () => {
  return (
    <main className="mx-auto w-full flex  max-w-3xl flex-1">
      <div className="py-24 sm:py-28">
        <h1 className="bg-gradient-to-r from-purple-600 via-pink-600 to-blue-600 bg-clip-text text-4xl font-bold text-transparent text-white md:pb-4 md:text-6xl">
          Now.
        </h1>
        <div className="grid max-w-6xl grid-cols-1 items-center justify-center text-white">
          <h1 className="text-2xl font-bold text-white">I am working on... </h1>
          <ul className="ml-4 mt-4 list-disc">
            <li>Senior IT Support.</li>
            <li>Learn DevOps for improve my skill and career in IT jobs</li>
            <li>Developing IT content on Instagram, Youtube and Tiktok.</li>
            <li>
              Creating an businees with my friends in tech that help people
              problem with their laptop and computer{" "}
              <a
                href="https://aitigik.id/"
                className="underline hover:text-gray-300"
                target="_blank"
              >
                AitiGik "Computer and Laptop Repair"
              </a>
              .
            </li>
            <li>Growing as an individual and reading lots of books.</li>
          </ul>
        </div>
      </div>
    </main>
  )
}

export default NowPage
